# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'publish', 'ordering': ('-publish',), 'permissions': [('post_editor', 'Post Editor')], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
